### ISSUE TITLE
PropTypes generation does not work for functional components that returns another function

### ISSUE THREAD

**Issue by Ifgen09** [dpzxsm/ReactPropTypes-Plugin#8]
Hi,
first of all - thank you for this plugin. I find it very convenient for myself.

But there is some unexpected behaviour:
PropTypes were not generated for functional components that returns another function that returns some jsx markup.
![phpstrom-proptypegenerate-issue](https://user-images.githubusercontent.com/7497949/47065854-0bc95b80-d1ed-11e8-814d-b45943349bbc.gif)

Ubuntu 18.04, PhpStorm 2018.2.2

**Comment by dpzxsm** [comment]
@Ifgen09 Because it's really hard to distinguish functional components,  so i assert  functional components must reuturn jsx markup, rather than return a new functional component or a function that return jsx markup。if you want so ,  i will provide a option in the plugin's setting to remove this assert, but I don't promise to make sure that this is one valid functional component 。

**Comment by Ifgen09** [comment]
@dpzxsm 
sorry, what do you mean by ? 

> option in the plugin's setting to remove this assert

**Comment by dpzxsm** [comment]
@Ifgen09 Well, I mean it is easy to fixed it, bu I dont's like this way to support for functional components。If you want it, i will provide a option in Settting, like this:
￼
![1540175841509](https://user-images.githubusercontent.com/20736977/47276006-c9d25800-d5e6-11e8-9b84-fd1a0d03b78c.jpg)

**Comment by Ifgen09** [comment]
@dpzxsm 
it would be very good. thanks

**Comment by dpzxsm** [comment]
![1540545867587](https://user-images.githubusercontent.com/20736977/47557731-08984300-d944-11e8-9297-405c14630a27.jpg)
In v1.1.3 , you can open the option to resolve it , like this.
